# theme
remote_theme: andy840119/tameowder-theme

# header
title: osu!Karaoke
description: Offical site for karaoke ruleset
baseurl: "/"
url: "https://osu-karaoke.github.io"

# Aux links for the upper right navigation
aux_links:
  "osu!karaoke on GitHub":
    - "//github.com/osu-karaoke/"

# navigation
discord_id: 299006062323826688

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2019-2020 andy840119. Distributed by an <a href=\"https://github.com/osu-karaoke/\">GPL V3 license.</a>"
