# theme
remote_theme: andy840119/tameowder-theme

# header
title: karaoke --dev
description: Offical site for sharing anything about karaoke development.
baseurl: "/"
url: "https://karaoke-dev.github.io"

# Aux links for the upper right navigation
aux_links:
  "karaoke --dev on GitHub":
    - "//github.com/karaoke-dev/"

# navigation
discord_id: 299006062323826688

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2019-2020 andy840119. Distributed by an <a href=\"https://github.com/karaoke-dev/\">GPL V3 license.</a>"
